---
output: 
  pdf_document: 
    keep_tex: yes
    includes:
        in_header: ~/Desktop/research/preamble_common.tex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE, 
  warning = FALSE, 
  message = FALSE,
  include = FALSE,
  cache = TRUE,
  tidy.opts=list(width.cutoff=60),
  tidy=TRUE,
  fig.align = "center",
  out.width = "60%"
)
```

### General Form of Distributions

$$F(x) = G\{H_{\xi}{(\frac{x}{\sigma})} \} $$

### Parametric Families  

1. $G(v) = v^\kappa, \ \kappa > 0$ 
$$F_1(x) = \{1 - [1 + \xi(\frac{x}{\sigma})]^{-1/\xi} \}^\kappa$$
$$f_1(x) = \frac{\kappa}{\sigma}[1 + \xi (\frac{x}{\sigma})]^{-(1/\xi + 1)}\{1 - [1+\xi(\frac{x}{\sigma})]^{-1/\xi} \} ^{\kappa-1}$$
```{r echo=FALSE}
g1_pdf <- function(x, sigma = sigma, xi = xi, kappa = kappa) {
  lpdf <- log(kappa) - log(sigma) - (1/xi + 1) * log(1 + xi * (x/sigma)) + 
    (kappa-1) * log(1 - (1 + xi * (x/sigma))^(-1/xi))
  return(exp(lpdf))
}

curve(g1_pdf(x, sigma = 1, xi = 0.5, kappa = 1), xlim = c(0, 7.5))
curve(g1_pdf(x, sigma = 1, xi = 0.5, kappa = 2), xlim = c(0, 7.5), add = TRUE, col = 'blue')
curve(g1_pdf(x, sigma = 1, xi = 0.5, kappa = 5), xlim = c(0, 7.5), add = TRUE, col = 'red')
```

$$F_1^{-1}(U) = \frac{\sigma}{\xi} [(1-U^{1/\kappa})^{-\xi} - 1]$$
```{r eval=FALSE, include=FALSE}
g1_cdf <- function(x, sigma = sigma, xi = xi, kappa = kappa) {
  (1 - (1 + xi * (x/sigma))^(-1/xi))^kappa
}

g1_cdf_inv <- function(u, sigma = sigma, xi = xi, kappa = kappa) {
  (sigma/xi) * ((1-u^(1/kappa))^-xi - 1)
}

u1000 <- runif(1000000)
```

```{r eval=FALSE, include=FALSE}
hist_cdf <- g1_cdf_inv(u1000, sigma = 1, xi = 0.5, kappa =2)
hist(g1_cdf_inv(u1000, sigma = 1, xi = 0.5, kappa = 2), breaks = seq(0, max(hist_cdf) + 1, 0.1),  xlim = c(0,10), freq = FALSE)
curve(g1_pdf(x, sigma = 1, xi = 0.5, kappa = 2), xlim = c(0, 7.5), add = TRUE, col = 'red')
```


2. $G(v) = pv^{\kappa_1} + (1-p)v^{\kappa_2}, \ \kappa_1, \kappa_2 >0$
$$F_2(x) = p\{1 - [1 + \xi(\frac{x}{\sigma})]^{-1/\xi} \}^{\kappa_1} + (1-p)\{1 - [1 + \xi(\frac{x}{\sigma})]^{-1/\xi} \}^{\kappa_2}$$
$$f_2(x) = \frac{1}{\sigma}[1 + \xi (\frac{x}{\sigma})]^{-(1/\xi + 1)}\left(\kappa_1p\{1 - [1+\xi(\frac{x}{\sigma})]^{-1/\xi} \} ^{\kappa_1-1} + \kappa_2(1-p)\{1 - [1+\xi(\frac{x}{\sigma})]^{-1/\xi} \} ^{\kappa_2-1}\right)$$
```{r echo=FALSE}
g2_pdf <- function(x, sigma = sigma, xi = xi, kappa1 = kappa1, kappa2 = kappa2, p = p) {
  lpdf <- -(1/xi + 1) * log(1 + xi * (x/sigma)) - log(sigma) + 
    log(kappa1 * p * (1 - (1 + xi * (x/sigma))^(-1/xi))^(kappa1 - 1) + kappa2 * (1-p) * (1 - (1 + xi * (x/sigma))^(-1/xi))^(kappa2 - 1)) 
  return(exp(lpdf))
}

curve(g2_pdf(x, sigma = 1, xi = 0.5, kappa1 = 1, kappa2 = 1, p = 0.5), xlim = c(0, 7.5), ylab = "Density")
curve(g2_pdf(x, sigma = 1, xi = 0.5, kappa1 = 2, kappa2 = 5, p = 0.5), xlim = c(0, 7.5), add = TRUE, col = 'blue')
curve(g2_pdf(x, sigma = 1, xi = 0.5, kappa1 = 2, kappa2 = 10, p = 0.5), xlim = c(0, 7.5), add = TRUE, col = 'red')
```

```{r eval=FALSE, include=FALSE}
g2_cdf <- function(x, sigma = sigma, xi = xi, kappa1 = kappa1, kappa2 = kappa2, p = p) {
  p * (1 - (1 + xi * (x/sigma))^(-1/xi))^kappa1 + (1-p) * (1 - (1 + xi * (x/sigma))^(-1/xi))^kappa2
}
```

```{r eval=FALSE, include=FALSE}
curve(g2_cdf(x, sigma = 1, xi = 0.5, kappa1 = 2, kappa2 = 2, p = 0.5), xlim = c(0, 50), ylab = "CDF")
curve(g2_cdf(x, sigma = 1, xi = 0.5, kappa1 = 2, kappa2 = 5, p = 0.5), xlim = c(0, 50), add = TRUE, col = 'blue')
curve(g2_cdf(x, sigma = 1, xi = 0.5, kappa1 = 2, kappa2 = 10, p = 0.5), xlim = c(0, 50), add = TRUE, col = 'red')
```

```{r eval=FALSE, include=FALSE}
first <- TRUE
plot.new()
for (p in seq(0, 1, length.out = 25)) {
  curve(g2_cdf(x, sigma = 1, xi = 0.5, kappa1 = 2, kappa2 = 10, p = p), xlim = c(0, 100), add = !first)
  first <- FALSE
}
rm('p')
```

<!-- Varying $p$, $\kappa_2 = 5$ -->
```{r eval=FALSE, include=FALSE}
first <- TRUE
for (p in seq(0, 1, length.out = 25)) {
  curve(g2_pdf(x, sigma = 1, xi = 0.5, kappa1 = 2, kappa2 = 5, p = p), ylab = "Density", ylim = c(0, 0.4), xlim = c(0, 7.5), add = !first)
  first <- FALSE
}
rm('p')
```


<!-- Varying $p$, $\kappa_2 = 10$ -->
```{r eval=FALSE, include=FALSE}
first <- TRUE
for (p in seq(0, 1, length.out = 25)) {
  curve(g2_pdf(x, sigma = 1, xi = 0.5, kappa1 = 2, kappa2 = 10, p = p), ylab = "Density", ylim = c(0, 0.4), xlim = c(0, 7.5), add = !first)
  first <- FALSE
}
rm('p')
```

<!-- random number generation using `uniroot` -->
```{r eval=FALSE, include=FALSE}
g2_inv <- function(y, sigma, xi, kappa1, kappa2, p){
  uniroot(function(x){g2_cdf(x, sigma, xi, kappa1, kappa2, p) - y},interval=c(0,100), extendInt = "yes")$root
}
g2_inv <- Vectorize(g2_inv)

U <- runif(1000,0,1) 
```

```{r eval=FALSE, include=FALSE}
X <- g2_inv(U, sigma = 1, xi = 0.5, kappa1 = 2, kappa2 = 2, p = 0.5)
hist(X, freq=FALSE, breaks = seq(0, max(X) + 1, 0.2), xlim=c(0,10))
curve(g2_pdf(x, sigma = 1, xi = 0.5, kappa1 = 2, kappa2 = 2, p = 0.5), xlim = c(0, 10), add = TRUE, col = 'blue')
```

```{r eval=FALSE, include=FALSE}
X <- g2_inv(U, sigma = 1, xi = 0.5, kappa1 = 2, kappa2 = 5, p = 0.5)
hist(X, freq=FALSE, breaks = seq(0, max(X) + 1, 0.2), xlim=c(0,10))
curve(g2_pdf(x, sigma = 1, xi = 0.5, kappa1 = 2, kappa2 = 5, p = 0.5), xlim = c(0, 10), add = TRUE, col = 'blue')
```

```{r eval=FALSE, include=FALSE}
X <- g2_inv(U, sigma = 1, xi = 0.5, kappa1 = 2, kappa2 = 10, p = 0.5)
hist(X, freq=FALSE, breaks = seq(0, max(X) + 1, 0.25), xlim=c(0,10))
curve(g2_pdf(x, sigma = 1, xi = 0.5, kappa1 = 2, kappa2 = 10, p = 0.5), xlim = c(0, 10), add = TRUE, col = 'blue')
```
<!-- \pagebreak -->

3. $G(v) = 1-Q_\delta\{(1-v)^\delta\}, \ \delta > 0, \ \ Q_\delta \sim \text{Beta}(1/\delta, 2)$
$$F_3(x) = 1 - Q_\delta\{[1 + \xi(\frac{x}{\sigma})]^{-\delta/\xi} \}, \ \ Q_\delta \stackrel{d}{=}\text{Beta}(1/\delta, 2)$$

$$f_3(x) = \frac{1 + \delta}{\delta\sigma}[1 + \xi (\frac{x}{\sigma})]^{-(1/\xi + 1)}\left(1 - [1+\xi(\frac{x}{\sigma})]^{-\delta/\xi} \right)$$


```{r}
g3_pdf <- function(x, sigma = sigma, xi = xi, delta = delta) {
  lpdf <- log(1 + delta) - log(delta * sigma) - (1/xi + 1) * log(1 + xi * (x/sigma)) + 
    log(1 - (1 + xi * (x/sigma))^(-delta/xi))
  return(exp(lpdf))
}
```

```{r}
curve(g3_pdf(x, sigma = 1, xi = 0.5, delta = 25), xlim = c(0, 7), ylim = c(0, 1), ylab = "pdf", col = "red")
curve(g3_pdf(x, sigma = 1, xi = 0.5, delta = 5), xlim = c(0, 7), add = TRUE, col = 'blue')
curve(g3_pdf(x, sigma = 1, xi = 0.5, delta = 3), xlim = c(0, 7), add = TRUE, col = 'green')
```

$$F_3^{-1}(U) = \frac{\sigma}{\xi}\left([Q_\delta^{-1}\{1 - U\}]^{-\xi/\delta} - 1\right)$$

```{r echo=TRUE}
g3_cdf_inv <- function(u, sigma = sigma, xi = xi, delta = delta) {
  (sigma/xi) * ((qbeta((1-u), (1/delta), 2)^(-xi/delta)) - 1)
}

g3_rng <- function(n, sigma = sigma, xi = xi, delta = delta) {
  g3_cdf_inv(runif(n), sigma, xi, delta)
}
```

<!-- \pagebreak -->
<!-- $\delta = 1$ -->

```{r echo=FALSE}
d <- 1
pts <- g3_rng(n = 1000, sigma = 1, xi = 0.5, delta = d)
hist(pts, freq=FALSE, breaks = seq(0, max(pts) + 1, 0.25), xlim = c(0,7), ylim = c(0, 0.5))
curve(g3_pdf(x, sigma = 1, xi = 0.5, delta = d), xlim = c(0, 7), add = TRUE, col = 'blue')
```

<!-- $\delta = 3$ -->

```{r echo=FALSE}
d <- 3
pts <- g3_rng(n = 1000, sigma = 1, xi = 0.5, delta = d)
hist(pts, freq=FALSE, breaks = seq(0, max(pts) + 1, 0.25), xlim = c(0,7), ylim = c(0, 0.6))
curve(g3_pdf(x, sigma = 1, xi = 0.5, delta = d), xlim = c(0, 7), add = TRUE, col = 'blue')
```

<!-- $\delta = 5$ -->

```{r echo=FALSE}
d <- 5
pts <- g3_rng(n = 1000, sigma = 1, xi = 0.5, delta = d)
hist(pts, freq=FALSE, breaks = seq(0, max(pts) + 1, 0.25), xlim = c(0,7), ylim = c(0, 0.6))
curve(g3_pdf(x, sigma = 1, xi = 0.5, delta = d), xlim = c(0, 7), add = TRUE, col = 'blue')
```


4. $G(v) = [1-Q_\delta\{(1-v)^\delta\}]^{\kappa/2}, \ \kappa, \delta > 0$
$$F_4(x) = [1 - Q_\delta\{[1 + \xi(\frac{x}{\sigma})]^{-\delta/\xi} \}]^{\kappa/2}, \ \ Q_\delta \stackrel{d}{=}\text{Beta}(1/\delta, 2)$$


 
