---
title: "scores_tables"
output: 
  pdf_document: 
    keep_tex: yes
date: "2023-06-26"
---

```{r eval=FALSE, message=FALSE, include=FALSE}
library(kableExtra)
library(tidyr)
library(dplyr)
library(stringr)
library(tibble)

# joint model compared with individual models
twcrps_joint <- readRDS("~/Desktop/research/egpd-fires/full-model/fire-sims/model_comparison/joint_scores.RDS")$twcrps
g1_data_twcrps <- readRDS("~/Desktop/research/egpd-fires/full-model/fire-sims/model_comparison/g1_data_twcrps.RDS")
twcrps_joint <- twcrps_joint %>% filter(grepl("gamma-ri_1000iter", model))
twcrps_full <- twcrps_joint %>% rbind(g1_data_twcrps) %>% mutate(twcrps = twcrps * 10e2)

test_twcrps_ranked <- twcrps_full %>% filter(train == FALSE) %>% 
  group_by(model) %>% 
  summarize(mean_twcrps = mean(twcrps, na.rm = TRUE)) %>% arrange(mean_twcrps)
top_mod_test_twcrps <- as.character(test_twcrps_ranked$model[1])
test_twcrps_comp <- twcrps_full %>% filter(train == FALSE) %>% 
  dplyr::select(c(draw, model, twcrps)) %>% 
  pivot_wider(names_from = model, values_from = twcrps, values_fill = NA) %>% 
  mutate(across(.cols = -draw, ~ .x - get(top_mod_test_twcrps))) %>% 
  pivot_longer(cols = -draw, names_to = "model") %>%
  group_by(model) %>%
  summarize(mean_diff = mean(value[is.finite(value)]), sd_diff = sd(value[is.finite(value)])) %>% arrange(mean_diff)
test_twcrps_comp <- test_twcrps_comp %>% rename(twcrps_mean_diff = mean_diff, twcrps_sd_diff = sd_diff)

loglik_count <- readRDS("~/Desktop/research/egpd-fires/full-model/fire-sims/model_comparison/joint_scores.RDS")$loglik_count
count_scores <- readRDS("~/Desktop/research/egpd-fires/full-model/fire-sims/model_comparison/count_scores.RDS")
loglik_full <- loglik_count %>% rbind(count_scores)
test_ll_total_ranked <- loglik_full %>% filter(train == FALSE) %>% 
  group_by(draw, model, train) %>%
  summarize(loglik_total = sum(loglik)) %>% ungroup() %>%
  group_by(model) %>% 
  summarize(med_test_ll = median(loglik_total)) %>% arrange(-med_test_ll)
top_mod_total_test <- as.character(test_ll_total_ranked$model[1])
test_ll_total_comp <- loglik_full %>% filter(train == FALSE) %>% 
  group_by(draw, model, train) %>%
  summarize(loglik_total = sum(loglik)) %>% ungroup() %>%
  dplyr::select(c(draw, model, loglik_total)) %>% 
  pivot_wider(names_from = model, values_from = loglik_total, values_fill = NA) %>% 
  mutate(across(.cols = -draw, ~ .x - get(top_mod_total_test))) %>% 
  pivot_longer(cols = -draw, names_to = "model") %>%
  group_by(model) %>%
  summarize(med_diff = median(value[is.finite(value)]), sd_diff = sd(value[is.finite(value)])) %>% arrange(-med_diff) %>% rename(loglik_mean_diff = med_diff, loglik_sd_diff = sd_diff)
test_ll_total_comp


ll_joint_burn <- readRDS("~/Desktop/research/egpd-fires/full-model/fire-sims/model_comparison/joint_scores.RDS")$loglik_burn
g1_data_loglik <- readRDS("~/Desktop/research/egpd-fires/full-model/fire-sims/model_comparison/g1_data_loglik.RDS")
loglik_joint_burn <- ll_joint_burn %>% rbind(g1_data_loglik)

test_ll_total_ranked <- loglik_joint_burn %>% filter(train == FALSE) %>% 
  group_by(draw, model, train) %>%
  summarize(loglik_total = sum(loglik)) %>% ungroup() %>%
  group_by(model) %>% 
  summarize(med_test_ll = median(loglik_total)) %>% arrange(-med_test_ll)
top_mod_total_test <- as.character(test_ll_total_ranked$model[1])
test_ll_total_comp <- loglik_joint_burn %>% filter(train == FALSE) %>% 
  group_by(draw, model, train) %>%
  summarize(loglik_total = sum(loglik)) %>% ungroup() %>%
  dplyr::select(c(draw, model, loglik_total)) %>% 
  pivot_wider(names_from = model, values_from = loglik_total, values_fill = NA) %>% 
  mutate(across(.cols = -draw, ~ .x - get(top_mod_total_test))) %>% 
  pivot_longer(cols = -draw, names_to = "model") %>%
  group_by(model) %>%
  summarize(med_diff = median(value[is.finite(value)]), sd_diff = sd(value[is.finite(value)])) %>% arrange(-med_diff) %>% rename(loglik_mean_diff = med_diff, loglik_sd_diff = sd_diff)
test_ll_total_comp

joint_scores <- test_twcrps_comp_1000iter %>% left_join(test_ll_total_comp_1000iter)
joint_scores <- joint_scores %>% 
  mutate(gamma = case_when(grepl("gamma-ri", model) ~ 'ri',
                           TRUE ~ 'cst'))

joint_scores %>% mutate_if(is.numeric, round, 3) %>% dplyr::select(-model) %>% relocate('gamma', .before = 'twcrps_mean_diff') %>%
  rename("$\\gamma$" = gamma, "Mean_tw" = twcrps_mean_diff, "SD_tw" = twcrps_sd_diff, "Mean_ll" = loglik_mean_diff, "SD_ll" = loglik_sd_diff) %>%
  kable(., format='latex', booktabs=T, escape = F)
  
  # %>% add_header_above(c(" "=1, "twCRPS" = 2, "Log-likelihood" = 2)) %>%
  # # collapse_rows(columns = 1, latex_hline = "major", valign = "middle")

```

```{r eval=FALSE, include=FALSE}
library(kableExtra)
library(tidyr)
library(dplyr)
library(stringr)
library(tibble)

burn_scores <- readRDS("~/Desktop/research/egpd-fires/full-model/fire-sims/model_comparison/burn_scores.RDS")
twcrps_full <- burn_scores$twcrps
loglik_full <- burn_scores$loglik
test_twcrps_ranked <- twcrps_full %>% filter(train == FALSE) %>% mutate(twcrps = twcrps * 10e2) %>%
  group_by(model) %>% 
  summarize(mean_twcrps = mean(twcrps, na.rm = TRUE)) %>% arrange(mean_twcrps)
top_mod_test_twcrps <- as.character(test_twcrps_ranked$model[1])
test_twcrps_comp <- twcrps_full %>% filter(train == FALSE) %>% 
  dplyr::select(c(draw, model, twcrps)) %>% 
  pivot_wider(names_from = model, values_from = twcrps, values_fill = NA) %>% 
  mutate(across(.cols = -draw, ~ .x - get(top_mod_test_twcrps))) %>% 
  pivot_longer(cols = -draw, names_to = "model") %>%
  group_by(model) %>%
  summarize(mean_diff = mean(value[is.finite(value)]), sd_diff = sd(value[is.finite(value)])) %>% arrange(mean_diff) %>%
  rename(twcrps_mdiff = mean_diff, twcrps_sd = sd_diff)
test_twcrps_comp

test_loglik_ranked <- loglik_full %>% filter(train == FALSE) %>% 
  group_by(draw, model, train) %>%
  summarize(loglik_total = sum(loglik)) %>% ungroup() %>%
  group_by(model) %>% 
  summarize(med_test_ll = median(loglik_total)) %>% arrange(-med_test_ll)
top_mod_test_loglik <- as.character(test_loglik_ranked$model[1])
test_loglik_comp <- loglik_full %>% filter(train == FALSE) %>% 
  group_by(draw, model, train) %>%
  summarize(loglik_total = sum(loglik)) %>% ungroup() %>%
  dplyr::select(c(draw, model, loglik_total)) %>% 
  pivot_wider(names_from = model, values_from = loglik_total, values_fill = NA) %>% 
  mutate(across(.cols = -draw, ~ .x - get(top_mod_test_loglik))) %>% 
  pivot_longer(cols = -draw, names_to = "model") %>%
  group_by(model) %>%
  summarize(med_diff = median(value[is.finite(value)]), sd_diff = sd(value[is.finite(value)])) %>% arrange(-med_diff) %>%
  rename(loglik_mdiff = med_diff, loglik_sd = sd_diff)
test_burns_all_scores <- test_twcrps_comp %>% left_join(test_loglik_comp)

test_burns_all_scores <- test_burns_all_scores %>% 
  mutate(kappa = case_when(grepl('sigma', model) ~ 'reg',
                           grepl('g1_xi-ri', model) ~ 'reg',
                               TRUE ~ 'ri'),
         sigma = case_when(grepl('kappa-ri', model) ~ 'reg',
                           grepl('g1_xi-ri', model) ~ 'reg',
                           grepl('sigma-ri', model) ~ 'ri',
                           grepl('sigma-cst', model) ~ 'cst'),
         xi = case_when(grepl('xi-ri', model) ~ 'ri',
                        TRUE ~ NA)) %>%
  filter(!grepl("nu", model)) %>%
  separate_wider_delim(cols = model, delim = "_", names = "model", too_many = "drop")

test_burns_all_scores %>% arrange(model, twcrps_mdiff) %>% 
  relocate(c('kappa', 'sigma', 'xi'), .before = 'twcrps_mdiff') %>% mutate_if(is.numeric, round, 3) %>% 
    mutate(kappa = case_when(kappa == 'reg' & model != 'lognorm' ~ "$\\checkmark$", 
                             kappa == 'reg' & model == 'lognorm' ~ "($\\checkmark$)", 
                             kappa == 'ri' ~ "--"),
           sigma = case_when(sigma == 'reg' ~ "$\\checkmark$",
                             sigma == 'ri' ~ "--",
                             sigma == 'cst' ~ "*"),
           xi = case_when(xi == 'reg' ~ "$\\checkmark$",
                          xi == 'ri' ~ "--"),
           model = case_when(model == 'g1' ~ "$G_1$",
                             model == 'g2' ~ "$G_2$",
                             model == 'lognorm' ~ "Lognormal")) %>% 
  rename("$\\kappa$($\\mu$)" = kappa, "$\\sigma$" = sigma, "$\\xi$" = xi, "Model" = model) %>% 
  kable(., format='latex', align = 'c', booktabs=T, escape = F) %>% 
  collapse_rows(columns = 1, latex_hline = "major", valign = "middle")
```



```{r echo=FALSE, message=FALSE}
library(kableExtra)
library(tidyr)
library(dplyr)
library(stringr)
library(tibble)
loglik_count <- readRDS("~/Desktop/research/egpd-fires/full-model/fire-sims/model_comparison/count_scores.RDS")
test_ll_total_ranked <- loglik_count %>% filter(train == FALSE) %>% 
  group_by(draw, model, train) %>%
  summarize(loglik_total = sum(loglik)) %>% ungroup() %>%
  group_by(model) %>% 
  summarize(med_test_ll = median(loglik_total)) %>% arrange(-med_test_ll)
top_mod_total_test <- as.character(test_ll_total_ranked$model[1])
test_ll_total_comp <- loglik_count %>% filter(train == FALSE) %>% 
  group_by(draw, model, train) %>%
  summarize(loglik_total = sum(loglik)) %>% ungroup() %>%
  dplyr::select(c(draw, model, loglik_total)) %>% 
  pivot_wider(names_from = model, values_from = loglik_total, values_fill = NA) %>% 
  mutate(across(.cols = -draw, ~ .x - get(top_mod_total_test))) %>% 
  pivot_longer(cols = -draw, names_to = "model") %>%
  group_by(model) %>%
  summarize(med_diff = median(value[is.finite(value)]), sd_diff = sd(value[is.finite(value)])) %>% arrange(-med_diff) %>% rename(loglik_med_diff = med_diff, loglik_sd_diff = sd_diff)
test_ll_total_comp

table_ll_counts <- test_ll_total_comp %>%
  mutate(lambda = 'reg',
         pi = case_when(grepl('pi-ri', model) ~ 'ri',
                        grepl('all-reg', model) ~ 'reg',
                        TRUE ~ 'NA'),
         delta = case_when(grepl('_er_', model)  ~ 'ri',
                           grepl('zip', model) ~ 'NA',
                           TRUE ~ 'cst')) %>%
  separate_wider_delim(cols = model, delim = "_", names = c("model", "submodel"), too_many = "drop") %>%
  rename(mdiff = loglik_med_diff, sdiff = loglik_sd_diff)

table_ll_counts %>% arrange(model) %>%
  relocate(c('lambda', 'pi', 'delta'), .before = 'mdiff') %>% mutate_if(is.numeric, round, 3) %>%
    mutate(lambda = case_when(lambda == 'reg' ~ "$\\checkmark$",
                             TRUE ~ NA ),
           pi = case_when(pi == 'reg' ~ "$\\checkmark$",
                             pi == 'ri' ~ "--",
                             pi == 'cst' ~ "*"),
           delta = case_when(delta == 'reg' ~ "$\\checkmark$",
                             delta == 'ri' ~ "--",
                             delta == 'cst' ~ "*",
                             delta == 'NA' ~ ''),
           model = case_when(model == 'zinb' ~ "ZI-Negative Binomial",
                             model == 'zip' ~ "ZI-Poisson")) %>% select(-submodel) %>%
  rename("$\\lambda$" = lambda, "$\\pi$" = pi, "$\\delta$" = delta,
         "Median" = mdiff, "SD" = sdiff, "Model" = model) %>%
  kable(., format='latex', align = 'c', booktabs=T, escape = F) %>% add_header_above(c(" "=1, "Regression" = 3, "Difference" = 2)) %>%
  collapse_rows(columns = 1, latex_hline = "major", valign = "middle")

loglik_count_dataset <- readRDS("~/Desktop/research/egpd-fires/full-model/fire-sims/model_comparison/count_scores_dataset.RDS")
test_ll_dataset_total_ranked <- loglik_count_dataset %>% filter(train == FALSE) %>% 
  group_by(draw, model, train) %>%
  summarize(loglik_total = sum(loglik)) %>% ungroup() %>%
  group_by(model) %>% 
  summarize(med_test_ll = median(loglik_total)) %>% arrange(-med_test_ll)
top_mod_total_test <- as.character(test_ll_dataset_total_ranked$model[1])
test_ll_dataset_total_comp <- loglik_count_dataset %>% filter(train == FALSE) %>% 
  group_by(draw, model, train) %>%
  summarize(loglik_total = sum(loglik)) %>% ungroup() %>%
  dplyr::select(c(draw, model, loglik_total)) %>% 
  pivot_wider(names_from = model, values_from = loglik_total, values_fill = NA) %>% 
  mutate(across(.cols = -draw, ~ .x - get(top_mod_total_test))) %>% 
  pivot_longer(cols = -draw, names_to = "model") %>%
  group_by(model) %>%
  summarize(med_diff = median(value[is.finite(value)]), sd_diff = sd(value[is.finite(value)])) %>% arrange(-med_diff) %>% 
  rename(loglik_med_diff = med_diff, loglik_sd_diff = sd_diff)


data_scores <- test_ll_dataset_total_comp %>% 
  mutate(model = case_when(grepl("erc_fwi", model) ~ 'ERC-FWI',
                           grepl("fwi", model) ~ 'FWI',
                           grepl("erc", model) ~ 'ERC',
                           grepl("climate", model) ~ 'Climate')) %>%
  rename('Median' = loglik_med_diff, 'SD' = loglik_sd_diff, 'Model' = model)

data_scores %>% mutate_if(is.numeric, round, 3) %>%
  kable(., format='latex', booktabs=T, escape = F)

```


```{r eval=FALSE, include=FALSE}
library(kableExtra)
library(tidyr)
library(dplyr)
library(stringr)
library(tibble)

# joint model tables
twcrps_full <- readRDS("~/Desktop/research/egpd-fires/full-model/fire-sims/model_comparison/g1_data_twcrps.RDS")
twcrps_full <- twcrps_full %>% mutate(twcrps = twcrps * 10e2)
test_twcrps_ranked <- twcrps_full %>% filter(train == FALSE) %>% 
  group_by(model) %>% 
  summarize(mean_twcrps = mean(twcrps, na.rm = TRUE)) %>% arrange(mean_twcrps)
top_mod_test_twcrps <- as.character(test_twcrps_ranked$model[1])
test_twcrps_comp <- twcrps_full %>% filter(train == FALSE) %>% 
  dplyr::select(c(draw, model, twcrps)) %>% 
  pivot_wider(names_from = model, values_from = twcrps, values_fill = NA) %>% 
  mutate(across(.cols = -draw, ~ .x - get(top_mod_test_twcrps))) %>% 
  pivot_longer(cols = -draw, names_to = "model") %>%
  group_by(model) %>%
  summarize(mean_diff = mean(value[is.finite(value)]), sd_diff = sd(value[is.finite(value)])) %>% arrange(mean_diff) %>%
  rename(twcrps_mean_diff = mean_diff, twcrps_sd_diff = sd_diff)

total_ll <- readRDS("~/Desktop/research/egpd-fires/full-model/fire-sims/model_comparison/g1_data_loglik.RDS")
test_ll_total_ranked <- total_ll %>% filter(train == FALSE) %>% 
  group_by(draw, model, train) %>%
  summarize(loglik_total = sum(loglik)) %>% ungroup() %>%
  group_by(model) %>% 
  summarize(med_test_ll = median(loglik_total)) %>% arrange(-med_test_ll)
top_mod_total_test <- as.character(test_ll_total_ranked$model[1])
test_ll_total_comp <- total_ll %>% filter(train == FALSE) %>% 
  group_by(draw, model, train) %>%
  summarize(loglik_total = sum(loglik)) %>% ungroup() %>%
  dplyr::select(c(draw, model, loglik_total)) %>% 
  pivot_wider(names_from = model, values_from = loglik_total, values_fill = NA) %>% 
  mutate(across(.cols = -draw, ~ .x - get(top_mod_total_test))) %>% 
  pivot_longer(cols = -draw, names_to = "model") %>%
  group_by(model) %>%
  summarize(med_diff = median(value[is.finite(value)]), sd_diff = sd(value[is.finite(value)])) %>% arrange(-med_diff) %>% 
  rename(loglik_med_diff = med_diff, loglik_sd_diff = sd_diff)

joint_scores <- test_twcrps_comp %>% left_join(test_ll_total_comp)
joint_scores <- joint_scores %>% 
  mutate(model = case_when(grepl("erc_fwi", model) ~ 'ERC-FWI',
                           grepl("fwi", model) ~ 'FWI',
                           grepl("erc", model) ~ 'ERC',
                           grepl("climate", model) ~ 'Climate'))

joint_scores %>% mutate_if(is.numeric, round, 3) %>% 
  kable(., format='latex', booktabs=T, escape = F)
```

